### ISSUE TITLE
Charge current not applied if reboot with USB cable plugged.

### ISSUE THREAD

**Issue by sorgelig** [AndreiLux/Perseus-UNIVERSAL5410#23]
It seams, SDP settings (may be other too) are not applied if reboot with USB cable plugged. 
After reboot max/avg/now values are all 460ma, although sdp_input_curr and sdp_chrg_curr are 900ma.
After replugging the USB cable values jump to STweak defined values (in my case 900ma).

**Comment by AndreiLux** [comment]
The charger chip gets programmed in the boot loader and also before init at boot.

They also don't get applied when you change them live, and have to reconnect the cable.

I'm not sure I want to fix this since it gets convoluted in terms of code (telling the driver to reattach itself). I'll see what I can do if it can be managed in a clean way.

**Comment by sorgelig** [comment]
I think, only apply at boot is important to fix. Changing them live in STweaks is not important because usually you change it once and forget. 
But while developing i often need to reboot the phone. So it would be good to avoid replugging the cable after each reboot.

**Comment by AndreiLux** [comment]
I decided to forego this, won't be fixed or altered due to the nature of how the charger code works.

**Comment by sorgelig** [comment]
I've patched original table to put 900ma/1000ma as initial value for SDP.
Since circuit has automatic current adjustment, it shouldn't be a problem.
