### ISSUE TITLE
High Android OS usage and failure to enter deep sleep

### ISSUE THREAD

**Issue by vincentemerald** [AndreiLux/Perseus-UNIVERSAL5410#7]
After updating 3.1, seems like the battery drains fast and Android_OS consumes 45% of it. Also the CPU stays away for most of the time. Not sure what process is keeping it awake.

Baseband Version : I9500DDUBMEA
Build number : JDQ39.I9500XXUBMEA

**Comment by AndreiLux** [comment]
This has 95%tly nothing to do with the kernel.

**Comment by vincentemerald** [comment]
The reason i raised this as a bug was that i flashed back the Alpha-2.1 and everything seems to go back to normal with CPU going to sleep very well. Just testing it for the past 15 mins. Not sure if some rouge app doesnt like this new kernel. Will keep testing it further and update you on any findings. Appreciate your support on this issue.

**Comment by AndreiLux** [comment]
I could just reproduce this. Looking into it.

Older kernel versions here: https://www.dropbox.com/sh/l9iwbpelw3fz1d6/lwwcWk8UHO

**Comment by AndreiLux** [comment]
This was caused by the regmap interface having a mutex lock in its primitive which I was hooking the register values on.
I'm using regmap functions inside of the hook for various actions, but since the mutex was already locked in that point, it ended up in a deadlock.

Unlocking the mutex before the hook fixes the problem.

Issue solved for 3.2.

**Comment by sorgelig** [comment]
Can you update sources, please?

**Comment by AndreiLux** [comment]
I forgot to push, I'll do it when I'm home.
